import { Globe, Box, BookOpen, Clock } from "lucide-react";

export const projects = [
  {
    title: "HustleX",
    description: [
      "Designed and built a comprehensive productivity platform for developers with secure JWT authentication",
      "Developed multiple specialized modules for tracking skills, working hours, LeetCode progress, and coding contests",
      "Created interactive dashboards with real-time data visualization using Recharts",
      "Implemented responsive UI with Framer Motion animations and TailwindCSS",
      "Built category management system with custom hooks for efficient data organization",
    ],
    tech: [
      "React",
      "Express.js",
      "MongoDB",
      "Node.js",
      "TailwindCSS",
      "Framer Motion",
      "JWT",
      "Recharts",
      "Nodemailer",
    ],
    github: "https://github.com/ashparshp/hustlex",
    demo: "https://www.hustlex.in",
    icon: Clock,
  },
  {
    title: "ChronoSpace",
    description: [
      "Developed a full-featured blogging platform with rich text editor and content management",
      "Implemented role-based access with admin and user modes for content governance",
      "Built advanced search functionality for efficient content discovery",
      "Created nested comments/replies with real-time notifications",
      "Secured platform with JWT and Google OAuth authentication",
      "Integrated AWS S3 for scalable image storage with optimized performance",
    ],
    tech: [
      "React",
      "Node.js",
      "MongoDB",
      "AWS S3",
      "JWT",
      "TailwindCSS",
      "Google OAuth",
    ],
    github: "https://github.com/ashparshp/chronospace",
    demo: "https://chronospace.netlify.app",
    icon: Globe,
  },
  {
    title: "MediaFlow",
    description: [
      "Developed a YouTube-inspired backend using Node.js and Express.js",
      "Implemented authentication with JWT and bcrypt",
      "Integrated Cloudinary for media storage",
      "Utilized MongoDB with Mongoose for data persistence",
      "Designed comprehensive RESTful APIs",
    ],
    tech: ["Node.js", "Express.js", "MongoDB", "JWT", "Cloudinary", "Mongoose"],
    github: "https://github.com/Ashparshp/MediaFlow",
    icon: Box,
  },
  {
    title: "Library Management System",
    description: [
      "Built a full-stack library system with Golang (Gin, GORM) and React",
      "Designed RESTful APIs for seamless frontend-backend communication",
      "Integrated PostgreSQL and MongoDB Atlas for efficient data handling",
      "Implemented comprehensive library management features",
    ],
    tech: ["Go", "React", "PostgreSQL", "MongoDB", "Gin", "GORM"],
    github: "https://github.com/Ashparshp/LibraryReactGo",
    icon: BookOpen,
  },
];
